### ISSUE TITLE
Explore

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/19446-IntoTheDeep#1]
- [x] #2
- [x] #4
- [x] #5
- [x] #7
- [x] #8
- [x] #6

**Comment by GianBangayan** [comment]
General Points Guide - Ethan Fung
Stared points denote specific current focuses/points of interest
![image](https://github.com/user-attachments/assets/ff46bf8c-d92d-4d5d-9eaf-694cc878483c)![image](https://github.com/user-attachments/assets/575cc22c-d93c-4e55-ad5a-b5965f84b3a4)

**Comment by GianBangayan** [comment]
Some potential inspiration 
[https://www.youtube.com/watch?v=_UBPHONrCUU](url) 20077 The Indubitables **RI3D**
Robot Description
- single slide intake extension
- bucket + top-down roller + wrist transfer
- Active specimen placer
- Sliders + arm with bucket for outtake

[https://youtu.be/i2g_b54MEFI?si=wawU12YY4XHlmGze](url) 11115 Gluten Free **SKYSTONE**
Robot Description/Points of Interest
- two stage non-extending intake with auto-centering
- double reverse 4-bar 
- Side grabber

[https://www.youtube.com/watch?v=ukIq_HT5kog](url) 7129 Robo Raiders **RI30H**
Robot Description
- Simple light roller grabber with active wrist
- Single slide intake extension
- Vertical sliders
- "tilt" style bucket w/ servo - note bucket is made of foil/tape? (kinda interesting)
- Passive specimen placer - grabs from wall
     - made from a lexan backing, metal brackets, and 3d printed

**Comment by Ethan-Selvarajah** [comment]
**Initial Thoughts:**
My initial idea was the use of an arm that functioned similarly to Team [16379 Kookybotz's robot](https://www.youtube.com/watch?v=mT0KNbaz_80) from Centerstage last year. Specifically, I thought the use of a telescopic arm + claw would be interesting/optimal.

**Here are a few sketches of those initial ideas:**
![image](https://github.com/user-attachments/assets/0141b8a5-188e-4c9b-a698-6ac5e959b20a)
![image](https://github.com/user-attachments/assets/cc47114b-60f5-40f8-87eb-bdd77133f7d6)

**Based on these sketches, I had this idea for sample collection:**
1. The arm extends and the claw grabs the sample.
2. The claw has a servo which rotates 90*, and simultaneously the arm will retract into the robot.
3. The sample is then funneled into the robot where the transfer takes it in.
4. It is taken in using a compliant wheel and/or rotating surgical tubing.
5. The funnel ends up at the bottom of the sliders, which hosts a deposit box.
6. The sliders extend upwards and then rotates the box to slide it into the buckets.

I discovered this page for a [telescopic arm](https://www.thethriftybot.com/products/thrifty-telescoping-tube-kit). I watched their assembly video and found it both interesting and useful (if this idea was to be pursued).

**Hang Process:**
1. A hook attached to sliders.
2. [This](https://www.youtube.com/watch?v=IgF5ukoe12Y&feature=youtu.be) also attached to sliders somehow? Or maybe somewhere else. Need some way to ensure that the robot stays straight, otherwise the hang will be misaligned. 

The hang process is not refined either, and requires more thought.

**Additional Notes:**
These were just some of my initial thoughts, but it may not be the most efficient. I noticed that telescopic arms seemed very fast and stable, and the idea stemmed from there. Also, I am unsure if the transfer process would actually be efficient.
