### ISSUE TITLE
Pick Up

### ISSUE THREAD

**Issue by MariyaVla** [sta-titansrobotics/19446-IntoTheDeep#13]
Description As a driver, I want the intake to center the samples and turn it vertically into the chambers fast and easily. so that the robot can efficiently pick up the sample and transfer it to the claw.

Acceptance Criteria:
- the intake should be fast and efficient. 
- It should pick up the sample and turn it vertically. 
- It should be easy to move around in the submersible.

**Comment by cameronso5** [comment]
I started to work on the intake park of the robot by designing the sides that will funnel the specimen into the chamber. 

![Screenshot 2024-10-01 132637](https://github.com/user-attachments/assets/2e33d11a-e221-4a49-bd8a-84006675efbc)
V1

**Comment by cameronso5** [comment]
I made some changes to the intake by changing the floor to make it into a ramp and also added a weel hole so that it can support the ramp on the grond and to make it easier for the drivers to move the intake when it is in the submersible. I also added holes for the hex shafs and fixed some issues with the intake. 

![Screenshot 2024-10-01 132444](https://github.com/user-attachments/assets/bd915e29-cb71-4dba-8fd9-990881426751)
v2

**Comment by cameronso5** [comment]
add a hex shaft and the weels 
![Screenshot 2024-10-01 132608](https://github.com/user-attachments/assets/b1dc8444-181a-4d37-b4e9-7676590af029)
to the intake to make sure it fit

**Comment by cameronso5** [comment]
I worked on the motor placement for the rolers. I placed it there because it needs to move with the sliders and the intake needs to flip. I added some more support so it will help it for moving a lot when it is on. 

![Screenshot 2024-10-01 134105](https://github.com/user-attachments/assets/c53ab618-ba20-46e9-8783-344d9e39b51a)
