### ISSUE TITLE
Trapdoor

### ISSUE THREAD

**Issue by MariyaVla** [sta-titansrobotics/19446-IntoTheDeep#15]
This issue focuses on the trapdoor aspect of the transfer. The trapdoor will be assembled alongside the chamber and pick up to ensure a cohesive and smooth design. The trapdoor will be utilized to ensure the samples can be taken in, and then taken out once the chamber is rotated. This will be designed completely in Onshape and will be working by the end of Sprint 1.
-- @Ethan-Selvarajah

**Comment by Ethan-Selvarajah** [comment]
![image](https://github.com/user-attachments/assets/131bbd5e-c72b-4dde-9e21-4bbdaeb0b11f)
![image](https://github.com/user-attachments/assets/c8e4ce74-d053-4dd9-988c-3ee3fe216541)
V1 Trapdoor

**Comment by Ethan-Selvarajah** [comment]
![image](https://github.com/user-attachments/assets/e9b22938-6b57-4d5c-a0f8-e2f8e31f0c4f)
![image](https://github.com/user-attachments/assets/5651adc6-d8f1-4f7f-a95e-d628f9c92462)
- Made it more compact
- Added space in the bottom so it can move over top of the corner and not get caught
- Moved positioning of the shaft higher so that it doesn't interfere with sample entering (one more thing I want to discuss tomorrow)

**Comment by Ethan-Selvarajah** [comment]
![image](https://github.com/user-attachments/assets/86e0aa20-1c2e-4a9a-9371-b39550361108)
- Added hooks for rubber banding
- Reduced thickness of trapdoor

**Comment by Ethan-Selvarajah** [comment]
https://github.com/user-attachments/assets/10935598-aa44-4242-a4d2-7be8d72ef35a
Things to Fix:
- Turn the hex holes in the corners into 4mm circles so screws can go in
- Potentially move the hooks and holes (for the rubber band) to the center of the side of the trapdoor so that it's able to pull it back fully
- If I do the step above, then consider shortening the base of the rotation points on the corner
- Make the chamber longer so that the sample contacts a point closer to the center so it faces less resistance
- - Think: Pushing something closer to its rotation point vs. pushing something farther from its rotation point. 

Also, note for the video, that isn't how we will actually be rubber-banding it, it won't go all the way around.

**Comment by Ethan-Selvarajah** [comment]
![image](https://github.com/user-attachments/assets/d6588823-eaba-4d0b-96b5-5eff0b2b0af8)
![image](https://github.com/user-attachments/assets/4362b974-0058-45da-8cc8-d77fa004a280)
- Trapdoor was made longer to fulfill the longer chamber

**Comment by Ethan-Selvarajah** [comment]
Due to the intake design change regarding the rotation, the use of a trapdoor is now minimal. The only real usage is to prevent the sample from flying out, however, this is unlikely to occur. It seems as though the negatives (inefficiency) outweigh the benefits. If not removed, at the very least, the trapdoor will have to be updated, perhaps as some sort of flap near the intake (as if it does get flung, this is where it's most likely to happen).

**Comment by Ethan-Selvarajah** [comment]
![image](https://github.com/user-attachments/assets/5200b8e5-98b2-4a82-820d-98dec165a7e8)
One change was also made to the way the rubber bands work because that method was prior to snapping.

However, trapdoors are still being significantly revamped.
