### ISSUE TITLE
Sprint 3  - Design/Build/Test/Revise

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/19446-IntoTheDeep#28]

**Comment by MariyaVla** [comment]
### **CHAMBER & TRAPDOORS / TRANSFER**
Refer to #30 for details!

The basic goal of these components from the start was to allow the sample to be quickly placed in a container of sorts, from there moved around without a risk of it falling out, and finally a way for the sample to pass out of the container with ease. For this we were set on a chamber design with trapdoors. Throughout the sprints I had taken over this role and had created the finalized version of the component. 

### SUCCESSES
- The chamber efficiently picks up the sample without it getting caught (Before testing with intake)
- The chamber can move around side to side and up and down without the sample falling out (only through the intake hole which isnt an issue)
- The chamber aligns with the mounting of the sliders efficiently
- The chamber also aligns with the cut outs that are needed for the claw and the outtake
- The trapdoors have a good resistance that helps keep sample stable in movement 
- The trapdoors snap back into place at a perfect 90 degree angle without going inwards
- The trapdoors are 100% passive which is a benefit
- The rubber bands are well tensioned and are quick and easy to replace between games ( if they end up breaking, its much easier to repair than an active mechanism)

Overall there have been very many successes with the designs and all the objectives I have previously listen in the sprints have been achieved! 

### FAILURES AND NEXT STEPS
When it comes to failures, there are none with the current design. We will be testing the transfer with intake and outtake soon and maybe then I will have to do some minor edits. It is possible that when adding the intaking components such as high speed surgical tubing and an angled ramp, the transfer might not be smooth and it may have to be fixed. Or I may have to lower the resistance so that the outtake can actually pick up the sample with the high tension. But overall, there seems to be no flaws currently.

- @MariyaVla
