### ISSUE TITLE
Sprint 3 - Intake 

### ISSUE THREAD

**Issue by cameronso5** [sta-titansrobotics/19446-IntoTheDeep#30]
The goal of sprint 3 for the intake is to fully complete it. The intake is currently being designed in Onshape and prototyped as well with our parts. The various portions of the intake (ramp, funnel, and chamber) are being designed separately, and will then be placed together in one assembly. All portions of the intake are going to be tested, printed, and iterated.

The intake must work effectively so:
- Shouldn't be any jamming with the samples
- Should be able to pull the samples in very quickly (once the surgical tubing touches the sample, it should be pretty instant)

From a building perspective:
- Every piece should integrate seamlessly
- - No interference
- - All screws fit in the right places
- Foundation must be strong

From a driving perspective:
- Easily retrieve samples without extreme precision needed from drivers
- Should have a way to prevent multiple samples from being taken in, or have a way to get it out quickly to avoid penalties (note: this point may be brainstormed, but not fully implemented and finished by the end of this sprint)

The intake must be mounted properly on the sliders, but not fully onto the robot yet.

-@Ethan-Selvarajah

**Comment by MariyaVla** [comment]
https://github.com/user-attachments/assets/aba9acc6-f395-4367-a38c-4ca10610388a

**Comment by Ethan-Selvarajah** [comment]
https://github.com/user-attachments/assets/eabcc2b5-b846-4087-afd8-3b0749a7e203

We tested our intake in the field.

We noticed that we need to:
- Add two more surgical tubing pieces on the front roller (on the left and right) so it prevents the samples from getting jammed
- Add servo or some sort of clamping mechanism to chamber so that we can easily outtake any other unwanted samples
- Make the intake stronger because right now when its jostled it feels very flimsy (more metal)
- Trapdoor needs to be updated (completed now)

-@Ethan-Selvarajah @cameronso5

**Comment by Ethan-Selvarajah** [comment]
We are also waiting for an updated optake (smaller) to be printed because the current optake is too large, preventing proper testing.

-@Ethan-Selvarajah @cameronso5
