### ISSUE TITLE
System Integration

### ISSUE THREAD

**Issue by GianBangayan** [sta-titansrobotics/19446-IntoTheDeep#6]
The general layout on how the robot sub-systems will interact with each other, and their placements on the bot.

**Comment by GianBangayan** [comment]
![GianRobotSystemInt](https://github.com/user-attachments/assets/6d77ac38-2334-44e8-9e4f-c3bb9b6e6a87)
General robot rough drawing from Gian.
- Top-down tubing intake
- slide intake extension
- Vertical sliders 
- two stage hang, (slides + winch)
- outtake arm
- Passive specimen placer + bucket for samples

**Comment by GianBangayan** [comment]
![EthanRobotDraw1](https://github.com/user-attachments/assets/34c6e548-0f9f-4985-9e61-60ee88c30755)
![EthanRobotDraw2](https://github.com/user-attachments/assets/31897f15-16ad-4798-b332-0ea702d04397)
General robot Rough drawing from Ethan S.

- Ethan pls fill this out
- Telescopic intake extension
- Claw with rotating wrist mechanisim

**Comment by GianBangayan** [comment]
![image](https://github.com/user-attachments/assets/d8cc8321-97ad-4f80-9dbe-d30945f6027f)
General robot rough drawing from Ethan F.

**Comment by Ethan-Selvarajah** [comment]
**Initial Thoughts:**
My initial idea was the use of an arm that functioned similarly to Team [16379 Kookybotz's robot](https://www.youtube.com/watch?v=mT0KNbaz_80) from Centerstage last year. Specifically, I thought the use of a telescopic arm + claw would be interesting/optimal.

**Here are a few sketches of those initial ideas:**
![image](https://github.com/user-attachments/assets/0141b8a5-188e-4c9b-a698-6ac5e959b20a)
![image](https://github.com/user-attachments/assets/cc47114b-60f5-40f8-87eb-bdd77133f7d6)

**Based on these sketches, I had this idea for sample collection:**
1. The arm extends and the claw grabs the sample.
2. The claw has a servo which rotates 90*, and simultaneously the arm will retract into the robot.
3. The sample is then funneled into the robot where the transfer takes it in.
4. It is taken in using a compliant wheel and/or rotating surgical tubing.
5. The funnel ends up at the bottom of the sliders, which hosts a deposit box.
6. The sliders extend upwards and then rotates the box to slide it into the buckets.

I discovered this page for a [telescopic arm](https://www.thethriftybot.com/products/thrifty-telescoping-tube-kit). I watched their assembly video and found it both interesting and useful (if this idea was to be pursued).

**Hang Process:**
1. A hook attached to sliders.
2. [This](https://www.youtube.com/watch?v=IgF5ukoe12Y&feature=youtu.be) also attached to sliders somehow? Or maybe somewhere else. Need some way to ensure that the robot stays straight, otherwise the hang will be misaligned. 

The hang process is not refined either, and requires more thought.

**Additional Notes:**
These were just some of my initial thoughts, but it may not be the most efficient. I noticed that telescopic arms seemed very fast and stable, and the idea stemmed from there. Also, I am unsure if the transfer process would actually be efficient.

--Accidentally posted this under #1 but I'll move it here instead.
